#!/usr/bin/env python3
"""
gen_weights.py — Convert trained float weights to Verilog BNN localparam strings.

Workflow:
  1. Train a full-precision model externally (PyTorch / sklearn / etc.)
  2. Extract the weight vector for each neuron
  3. Run this script to produce copy-pasteable Verilog constants
  4. Paste output into your RTL module's localparam section

Usage:
  python3 gen_weights.py

Or import and call generate_verilog_params() from your training script.
"""

import numpy as np
from typing import List, Tuple


# ---------------------------------------------------------------------------
# Core conversion functions
# ---------------------------------------------------------------------------

def binarize(weights: np.ndarray) -> np.ndarray:
    """
    Threshold float weights to {0, 1}.
    Convention: positive  →  1  (agrees with +1 in {-1,+1} BNN)
                non-positive → 0  (maps -1 to 0 for XNOR encoding)
    """
    return (weights > 0).astype(int)


def popcount(bits: np.ndarray) -> int:
    return int(np.sum(bits))


def optimal_threshold(n_inputs: int) -> int:
    """
    Default threshold = ceil(n/2).  Fires when strict majority of inputs match.
    Tune per neuron based on validation accuracy.
    """
    return (n_inputs + 1) // 2


def weights_to_verilog_param(
    weights_bin: np.ndarray,
    name: str = "W",
    n_bits: int = 8
) -> str:
    """
    Convert a binary weight array to a Verilog localparam literal.

    weights_bin[0] → x[0] (LSB), weights_bin[n-1] → x[n-1] (MSB).
    Verilog bit-string is written MSB-first (left to right).
    """
    if len(weights_bin) != n_bits:
        raise ValueError(f"Expected {n_bits} weights, got {len(weights_bin)}")
    # Reverse: MSB (index n-1) appears leftmost in Verilog string
    bits_str = ''.join(str(int(b)) for b in reversed(weights_bin))
    return f"localparam [{n_bits-1}:0] {name} = {n_bits}'b{bits_str};"


def threshold_to_verilog_param(thresh: int, name: str = "THRESH") -> str:
    n_bits = int(np.ceil(np.log2(thresh + 1))) + 1  # enough bits
    n_bits = max(n_bits, 4)                          # at least 4 for readability
    return f"localparam [{n_bits-1}:0] {name} = {n_bits}'d{thresh};"


def generate_verilog_params(
    neuron_weights: List[np.ndarray],
    thresholds: List[int] = None,
    weight_names: List[str] = None,
    threshold_names: List[str] = None,
) -> str:
    """
    Generate Verilog localparam declarations for one or more neurons.

    Args:
        neuron_weights  : list of 1-D float or binary arrays, one per neuron
        thresholds      : optional per-neuron integer thresholds;
                          defaults to ceil(n/2) for each
        weight_names    : optional names e.g. ["W0","W1"]
        threshold_names : optional names e.g. ["T0","T1"]

    Returns:
        Multi-line string ready to paste into Verilog.
    """
    n = len(neuron_weights)
    n_inputs = len(neuron_weights[0])

    if thresholds is None:
        thresholds = [optimal_threshold(n_inputs)] * n
    if weight_names is None:
        weight_names = [f"W{i}" if n > 1 else "W" for i in range(n)]
    if threshold_names is None:
        threshold_names = [f"T{i}" if n > 1 else "THRESH" for i in range(n)]

    lines = ["// Auto-generated by gen_weights.py — do not edit manually", ""]
    for i, (w_raw, thresh, wname, tname) in enumerate(
            zip(neuron_weights, thresholds, weight_names, threshold_names)):
        w_bin = binarize(np.asarray(w_raw, dtype=float))
        lines.append(f"// Neuron {i}: {popcount(w_bin)}/{n_inputs} positive weights, "
                     f"threshold={thresh}")
        lines.append(weights_to_verilog_param(w_bin, wname, n_inputs))
        lines.append(threshold_to_verilog_param(thresh, tname))
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Example: simulated trained weights (replace with your actual model output)
# ---------------------------------------------------------------------------

def example_single_neuron():
    print("=" * 60)
    print("Example 1: Single neuron (reproduces tiny_bnn_comb.v weights)")
    print("=" * 60)

    # Simulated trained float weights for 8-input perceptron
    w_float = np.array([0.31, 0.82, 0.55, -0.14, 0.73, 0.61, -0.40, 0.19])
    #                   x[0]  x[1]  x[2]   x[3]  x[4]  x[5]   x[6]  x[7]

    w_bin = binarize(w_float)
    print(f"Float weights : {w_float}")
    print(f"Binary weights: {w_bin}  (1=positive, 0=negative)")
    print()
    print(generate_verilog_params([w_float], weight_names=["W"],
                                  threshold_names=["THRESH"]))


def example_two_neurons():
    print("=" * 60)
    print("Example 2: Two neurons (tiny_bnn_2out.v)")
    print("=" * 60)

    w0 = np.array([-0.5,  0.7,  0.6,  0.1, -0.3,  0.8,  0.9, -0.2])
    w1 = np.array([ 0.4,  0.3, -0.6,  0.2,  0.9, -0.1,  0.5,  0.8])

    # Override threshold for neuron 1 (stricter)
    thresholds = [optimal_threshold(8), 5]
    print(generate_verilog_params([w0, w1], thresholds=thresholds))


def example_from_pytorch():
    """
    Illustrative snippet — not runnable without PyTorch and a trained model.

    In a real training loop you would do:

        import torch
        model = YourBNNModel()
        # ... train ...
        w_float = model.fc1.weight.detach().numpy()  # shape [n_out, n_in]
        for i, row in enumerate(w_float):
            print(generate_verilog_params([row], weight_names=[f"W{i}"]))
    """
    print("=" * 60)
    print("Example 3: PyTorch integration (pseudocode)")
    print("=" * 60)
    pseudocode = """
# After training:
import torch
w = model.fc.weight.detach().numpy()   # [n_neurons, n_inputs]
for i, row in enumerate(w):
    verilog = generate_verilog_params([row], weight_names=[f"W{i}"],
                                      threshold_names=[f"T{i}"])
    print(verilog)
"""
    print(pseudocode)


# ---------------------------------------------------------------------------
# Verification helper: compute expected output for a test vector
# ---------------------------------------------------------------------------

def predict(x: np.ndarray, w_bin: np.ndarray, thresh: int) -> int:
    """
    Software BNN inference — matches the Verilog exactly.
    x     : binary input vector {0,1}^n
    w_bin : binary weight vector {0,1}^n
    thresh: integer threshold
    """
    match = ~(np.array(x, dtype=np.uint8) ^ np.array(w_bin, dtype=np.uint8)) & 1
    return int(np.sum(match) >= thresh)


def generate_test_vectors(w_bin: np.ndarray, thresh: int, n_samples: int = 16) -> str:
    """
    Generate expected-output table for manual testbench population.
    """
    n = len(w_bin)
    rng = np.random.default_rng(42)
    lines = ["// x (hex)  expected_y  popcount"]
    for _ in range(n_samples):
        x = rng.integers(0, 2, size=n)
        y = predict(x, w_bin, thresh)
        x_int = int(''.join(str(b) for b in reversed(x)), 2)
        pc = int(np.sum(~(x ^ w_bin) & 1))
        lines.append(f"// 8'h{x_int:02X}      {y}           {pc}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    example_single_neuron()
    print()
    example_two_neurons()
    print()
    example_from_pytorch()

    print("=" * 60)
    print("Test vector generation (for testbench)")
    print("=" * 60)
    w_demo = binarize(np.array([-0.5, 0.7, 0.6, 0.1, -0.3, 0.8, 0.9, -0.2]))
    print(generate_test_vectors(w_demo, thresh=4, n_samples=8))
