// =============================================================================
// tiny_bnn_comb.v  —  Optimized Combinational Binary Neural Network Perceptron
// =============================================================================
// Architecture  : XNOR + popcount + threshold comparator
// Dataset       : Breast Cancer Wisconsin (sklearn, 569 samples)
// Task          : Malignant (y=0) vs Benign (y=1) — 89.5% test accuracy
// Inputs        : 8 binary bits (each = 1 feature binarized at training median)
// Output        : 1 bit  (y=1 → benign, y=0 → malignant)
// Gate estimate : ~55 GE  (well under 1000-gate budget)
// Latency       : 3 logic levels  (XNOR → adder tree → comparator)
//
// Feature → bit mapping (binarize at shown threshold before feeding hardware):
//   x[0] = (mean radius        > 13.2700)   w=0
//   x[1] = (mean perimeter     > 85.9800)   w=1
//   x[2] = (mean area          > 541.800)   w=1
//   x[3] = (mean concave pts   > 0.03260)   w=0
//   x[4] = (worst radius       > 14.9100)   w=0
//   x[5] = (worst perimeter    > 97.5900)   w=0
//   x[6] = (worst area         > 683.400)   w=0
//   x[7] = (worst concave pts  > 0.09720)   w=0
//
// Weights auto-generated by scripts/train_bnn.py
// Inference accuracy: BNN 89.5% | float logistic reg 87.7% (binary features)
//   Sensitivity (benign recall)    : 86.1%
//   Specificity (malignant recall) : 95.2%
// =============================================================================

`default_nettype none

module tiny_bnn_comb (
    input  wire [7:0] x,   // 8-bit binarized feature vector (see mapping above)
    output wire       y    // 1 = benign, 0 = malignant
);

    // -------------------------------------------------------------------------
    // Trained weights — auto-generated by scripts/train_bnn.py
    // w=1 → feature HIGH matches benign pattern
    // w=0 → feature LOW  matches benign pattern
    // -------------------------------------------------------------------------
    localparam [7:0] W      = 8'b00000110;   // trained on breast_cancer dataset
    localparam [3:0] THRESH = 4'd3;          // fire if >= 3 of 8 features match

    // -------------------------------------------------------------------------
    // Stage 1 : XNOR  (replaces multiply in float BNN)
    // match[i] = 1 when x[i] agrees with W[i]
    // -------------------------------------------------------------------------
    wire [7:0] match = ~(x ^ W);

    // -------------------------------------------------------------------------
    // Stage 2 : Popcount — balanced binary adder tree (3 levels, min depth)
    //   Level 1 : 4× half-adders  (pair sums)         ~8 GE
    //   Level 2 : 2× 2-bit adders                     ~14 GE
    //   Level 3 : 1× 3-bit adder                      ~16 GE
    // -------------------------------------------------------------------------
    wire ha0_s = match[0] ^ match[1];   wire ha0_c = match[0] & match[1];
    wire ha1_s = match[2] ^ match[3];   wire ha1_c = match[2] & match[3];
    wire ha2_s = match[4] ^ match[5];   wire ha2_c = match[4] & match[5];
    wire ha3_s = match[6] ^ match[7];   wire ha3_c = match[6] & match[7];

    wire [2:0] p01 = {ha0_c, ha0_s} + {ha1_c, ha1_s};
    wire [2:0] p23 = {ha2_c, ha2_s} + {ha3_c, ha3_s};
    wire [3:0] sum = {1'b0, p01} + {1'b0, p23};

    // -------------------------------------------------------------------------
    // Stage 3 : Threshold comparator
    // -------------------------------------------------------------------------
    assign y = (sum >= THRESH);

endmodule
